CREATE TABLE `sap_service_order_header_data`
(
            `ServiceOrder`                        varchar(10) NOT NULL,
			`ServiceOrderType`                    varchar(4) DEFAULT NULL,
			`ServiceOrderUUID`                    varchar(36) DEFAULT NULL,
			`ServiceOrderDescription`             varchar(40) DEFAULT NULL,
			`ServiceObjectType`                   varchar(10) DEFAULT NULL,
			`Language`                            varchar(2) DEFAULT NULL,
			`ServiceDocumentPriority`             varchar(1) DEFAULT NULL,
			`RequestedServiceStartDateTime`       varchar(80) DEFAULT NULL,
			`RequestedServiceEndDateTime`         varchar(80) DEFAULT NULL,
			`ServiceDocChangedDateTime`           varchar(80) DEFAULT NULL,
			`PurchaseOrderByCustomer`             varchar(35) DEFAULT NULL,
			`CustomerPurchaseOrderDate`           varchar(80) DEFAULT NULL,
			`ServiceOrderIsReleased`              varchar(1) DEFAULT NULL,
			`ServiceOrderIsCompleted`             varchar(1) DEFAULT NULL,
			`ServiceOrderIsRejected`              varchar(1) DEFAULT NULL,
			`SalesOrganization`                   varchar(4) DEFAULT NULL,
			`DistributionChannel`                 varchar(2) DEFAULT NULL,
			`Division`                            varchar(2) DEFAULT NULL,
			`SalesOffice`                         varchar(4) DEFAULT NULL,
			`SalesGroup`                          varchar(3) DEFAULT NULL,
			`ShipToParty`                         varchar(10) DEFAULT NULL,
			`BillToParty`                         varchar(10) DEFAULT NULL,
			`PayerParty`                          varchar(10) DEFAULT NULL,
			`ContactPerson`                       varchar(10) DEFAULT NULL,
			`ServiceDocGrossAmount`               varchar(13) DEFAULT NULL,
			`ServiceDocNetAmount`                 varchar(13) DEFAULT NULL,
			`ServiceDocTaxAmount`                 varchar(13) DEFAULT NULL,
			`TransactionCurrency`                 varchar(5) DEFAULT NULL,
			`ReferenceServiceRequest`             varchar(10) DEFAULT NULL,
			`ReferenceServiceContract`            varchar(10) DEFAULT NULL,
			`ReferenceServiceOrder`               varchar(80) DEFAULT NULL,
			`SrvcOrdCreditStatus`                 varchar(1) DEFAULT NULL,
			`ServiceOrderRejectionReason`         varchar(2) DEFAULT NULL,
  PRIMARY KEY (`ServiceOrder`)
) ENGINE = InnoDB
 DEFAULT CHARSET = utf8mb4;
